//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bonus_assignment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class item
    {
        public int item_id { get; set; }
        public string Names { get; set; }
        public decimal price { get; set; }
        public string image_url { get; set; }
        public int quantity { get; set; }
    }
}
